### ISSUE TITLE
Support loading external CSS files in configuration

### ISSUE THREAD

**Issue by alanrubin** [searls/jasmine-maven-plugin#102]
This is useful as for example we want to test with jasmine jquery if a DOM element is hidden (.toBeHidden()) and display: none is defined in the css classes.

If the css is not added to the specRunner, the test will fail. I know I can use a customized spec runner template, but it could be nice to support that out of the box.

**Comment by klieber** [comment]
Closing this as there is a work around using a custom spec runner and personally I don't think specs should have any dependencies on external style sheets.
