### ISSUE TITLE
WAR overlay source include

### ISSUE THREAD

**Issue by bbergstrom** [searls/jasmine-maven-plugin#119]
I have a base WAR project with that has many WAR overlay projects.  Both have JS source in them, and the overlays depend on the base.  I can only define one jsSrcDir, so I am left defining source includes from my target folder.  There has to be a better way to do this, no?

Snippet of my config:

``` xml
<jsSrcDir>${project.basedir}/</jsSrcDir>
<sourceIncludes>
  <include>target/artifact-name/js/**/*.js</include>
  <include>src/main/webapp/js/**/*.js</include>
</sourceIncludes>
```

Update:  That config only works if you build with jasmine disabled to populate the target, then run it after.  It was a pretty crappy solution in the first place.  Any ideas on this would be appreciated.

**Comment by richotaylor** [comment]
Thanks @bbergstrom this helped with our setup of this as well. We have similar war overlays.
