### ISSUE TITLE
WAR Overlay Support

### ISSUE THREAD

**Issue by litzebauer** [searls/jasmine-maven-plugin#125]
I am unpacking a WAR overlay to the target/jasmine directory before the jasmine-maven-plugin runs.  This works great during the test lifecycle however it doesn't work when using jasmine:bdd since the WAR overlay js files don't appear to be served by Jetty.  Is there are better way to do this that will work for both the test lifecycle and jasmine:bdd?

**Comment by klieber** [comment]
Closing this issue because it hasn't been active in over 3 years. If this is still an issue with the current version of the plugin please add a comment with the latest information on the issue and I will reopen it.
