### ISSUE TITLE
Support configuration per execution

### ISSUE THREAD

**Issue by david-mas** [searls/jasmine-maven-plugin#133]
I need 2 different configurations for 2 different executions. Here is the use case:
I want to run the test goal on the target, with minified resources, and the bdd goal on the src, to hot edit code and keep tests green. If there is only 1 configuration I cannot do this.
This is related to issue #22 (Source order not preserved)

Example of what I would expect:

            <plugin>
                <groupId>com.github.searls</groupId>
                <artifactId>jasmine-maven-plugin</artifactId>
                <version>1.2.0.0</version>
                <extensions>true</extensions>
                <executions>
                    <execution>
                        
                        <phase>integration-test</phase>
                        <id>test</id>
                        <goals>
                            <goal>test</goal>
                        </goals>
                        <configuration>
                            <jsSrcDir>${project.build.directory}/${project.build.finalName}/js-lib</jsSrcDir>
                            <sourceIncludes>
                                <include>angular.min-1.0.3.js</include>
                                <include>all.js</include>
                            </sourceIncludes>
                        </configuration>
                    </execution>
                    <execution>
                        <id>bdd</id>
                        <goals>
                            <goal>bdd</goal>
                        </goals>
                        <configuration>
                            <jsSrcDir>${project.basedir}/src/main/webapp/js-lib</jsSrcDir>
                            <sourceIncludes>
                                <include>angular.min-1.0.3.js</include>
                                <include>all.js</include>
                            </sourceIncludes>
                        </configuration>
                    </execution>
                </executions>
            </plugin>

**Comment by klieber** [comment]
This is already possible by specifying the `bdd` goal configuration at the plugin level and then overriding that configuration at the execution level for the  `test` goal.
