### ISSUE TITLE
hanging jasmine:test

### ISSUE THREAD

**Issue by rweng** [searls/jasmine-maven-plugin#143]
`mvn -X jasmine:test` hangs with the last printed output:

~~~
   require(specs, function() {
      window.reporter = new jasmine.JsApiReporter(); jasmine.getEnv().addReporter(reporter);
      if ('JsApiReporter' == 'HtmlReporter') {
        jasmine.getEnv().specFilter = function(spec) {
          return window.reporter.specFilter(spec);
        };
      }
      jasmine.getEnv().execute();
    });
  </script>
</body>
</html> to directory /Users/robin/Code/soc/soc-war/target/jasmine
~~~~

any idea why or how to debug this further? `jasmine:bdd` works fine with all tests passing btw.

**Comment by klieber** [comment]
Closing this issue because it hasn't been active in over 2 years. If this is still an issue with the current version of the plugin please add a comment with the latest information on the issue and I will reopen it.
