### ISSUE TITLE
[Cannot find function setProperty in object] run with WebDriver org.openqa.selenium.htmlunit.HtmlUnitDriver

### ISSUE THREAD

**Issue by hunglu** [searls/jasmine-maven-plugin#205]
Hi all, 

I got this error when use webdriverclassname is org.openqa.selenium.htmlunit.HtmlUnitDriver

Does any one solve this one ? in HTMLUnit site, I saw they was fixed this in the latest version. Does this plugin include the latest version of it ?

[INFO] Executing Jasmine Specs
Nov 14, 2013 11:19:55 AM com.gargoylesoftware.htmlunit.javascript.background.JavaScriptJobManagerImpl runSingleJob
SEVERE: Job run failed with unexpected RuntimeException: TypeError: Cannot find function setProperty in object [object C
SSStyleDeclaration]. (http://localhost:55501/src/test/lib/sencha-touch-all-debug.js#14053)
======= EXCEPTION START ========
EcmaError: lineNumber=[14053] column=[0] lineSource=[null] name=[TypeError] sourceName=[http://localhost:55501/src/test/
lib/sencha-touch-all-debug.js] message=[TypeError: Cannot find function setProperty in object [object CSSStyleDeclaratio
n]. (http://localhost:55501/src/test/lib/sencha-touch-all-debug.js#14053)]
com.gargoylesoftware.htmlunit.ScriptException: TypeError: Cannot find function setProperty in object [object CSSStyleDec
laration]. (http://localhost:55501/src/test/lib/sencha-touch-all-debug.js#14053)

Thanks,

**Comment by mwanji** [comment]
I'm having a similar problem:

> net.sourceforge.htmlunit.corejs.javascript.EcmaError: TypeError: Cannot find function bind in object function (type, props, children) {...}. (http://localhost:43065/webjars/react-with-addons.js#10254)

It runs fine in the browser and with FirefoxDriver. The only reference I can find to this problem is a [bug report](http://sourceforge.net/p/htmlunit/bugs/734/) that was fixed in 2008!

I'm running 2.0-alpha01 with selenium 2.44.0 (2.41.0 doesn't work with the current version of Firefox) and htmlunit 2.15 (current latest htmlunit).
