### ISSUE TITLE
Unable to run jasmine tests with Chrome WebDriver with 'args' capability

### ISSUE THREAD

**Issue by chrishenzie** [searls/jasmine-maven-plugin#222]
Hi Kyle!

Thanks again for your help / speedy reply to [this issue](https://github.com/searls/jasmine-maven-plugin/issues/217) I had with using ChromeWebDriver with your plugin. Unfortunately I'm still having issues.

My goal is to make use of the 'args' capability, mentioned [here](https://sites.google.com/a/chromium.org/chromedriver/capabilities) towards the bottom of the page. Looking at the Capability class I see it has a Map of &lt;String, String&gt;. I would like to use capabilities whose values are a list or boolean too. Is there any reason this map cannot be &lt;String, Object&gt;?

**Comment by paulpach** [comment]
See #325 for an example of how to do this.
