### ISSUE TITLE
Unable to change path of phantomjsdriver.log when using PhantomJSDriver

### ISSUE THREAD

**Issue by mfernandes-git** [searls/jasmine-maven-plugin#241]
Hello Everyone,

I am using : 
jasmine.maven.plugin.version = 1.3.1.5
phantomjs.binary.version = 1.9.7

When my tests run the file phantomjsdriver.log is created outside of the Target directory.
I have passed a good amount of time trying to change the path for this log file.  
I have tried defining WebDriverCapabilities for the PhantomJSDriver.
Nothing works.

If I understand correctly from : https://github.com/detro/ghostdriver 
I need to specify the path to the GhostDriver main/src.js script to use
Do I really need to have a copy GhostDriver around just to change the path for this log ?

Am I missing something obvious ?
Is there anything that can be done with the jasmine-maven-plugin to simplify this configuration?

Thanks for any help !

**Comment by kriegaex** [comment]
I would also like to know. The log file pollutes our Maven project root directory (`user.dir`). The log file belongs into *target*, though.

**Comment by CptS** [comment]
+1

**Comment by ChrisGrigg** [comment]
+1

**Comment by ihernaez** [comment]
+1

**Comment by php-coder** [comment]
+1

**Comment by mnr1** [comment]
+1

**Comment by rimomol** [comment]
+1

**Comment by valgussev** [comment]
+1

**Comment by mpongelupe** [comment]
+1

**Comment by klieber** [comment]
@kriegaex, PhantomJS is essentially a dead project so further development regarding PhantomJS really doesn't make sense.  See here for more information: https://github.com/ariya/phantomjs/issues/15344

There is an alpha version of the plugin available that uses headless Chrome available:
https://github.com/searls/jasmine-maven-plugin/releases/tag/jasmine-maven-plugin-3.0-alpha-01

Thanks for the reminder to close this issue.
