### ISSUE TITLE
make test goal threadsafe

### ISSUE THREAD

**Issue by sylvainlaurent** [searls/jasmine-maven-plugin#243]
I don't know if the test goal is threadsafe, but if I launch a mvn -T 2 on a multimodule maven project, I have this warning :

```
[WARNING] ***************************************************************** 
[WARNING] The following plugins are not marked @threadSafe in myWebApp:  
[WARNING] com.github.searls:jasmine-maven-plugin:1.3.1.3                    
[WARNING] ***************************************************************** 
```

Is is threadsafe or not ? if yes, the Mojo should declare it to avoid the warning. if not, this would be nice to make it threadsafe...

**Comment by JonMR** [comment]
I'd also be interested in where the potential pitfalls are.  We see test failures when we run -T 1C on a large multi-module project.  Typically what happens is WebDriver just times out.  We haven't been able to pinpoint exactly the root cause of the error though.

**Comment by CptS** [comment]
+1

**Comment by aquator** [comment]
Same thing as @JonMR, it would be really nice to have it threadsafe, a few modules using jasmine ruin the whole multithread build.

**Comment by aquator** [comment]
Any updates on this? It is really annoying that we are unable to use multi-thread builds.
