### ISSUE TITLE
Chrome

### ISSUE THREAD

**Issue by onknows** [searls/jasmine-maven-plugin#245]
How can make it use Chrome as the browser. I think it is possible but it doesn't seem to be documented how this can achieved.

**Comment by fchetouani** [comment]
Hello

before to write,
I checked the page http://searls.github.io/jasmine-maven-plugin/webdriver-customization.html

Does someone have a full example to use firefox web driver or chrome web driver with jasmine 2.2 
during the jasmine:test goal ?

Thank you

**Comment by fchetouani** [comment]
I just read that the next jasmine release will use headless chrome by default so I will upgrade when jasmine 3.0 will be available.

Thanks for your work.
