### ISSUE TITLE
Cannot preload sources from directory outside project

### ISSUE THREAD

**Issue by misinco** [searls/jasmine-maven-plugin#248]
In our configuration, our angular sources are stored in a directory outside the project directory that I'm trying to test.

Example:
  /prj1
       - pom.xml
       - src/main/javascript
       - src/test/javascript
  /angular
        - angular.js
        - other angular files

So in the prj1 pom.xml file, I have tried several different maven properties to preload the angular sources:
<code>
<preloadSources>
     <source>${basedir}/../angular/angular.js</source>
</preloadSources>
</code>
Pretty much any maven property I try to use in order to get a directory within prj1 and navigate to a relative path, translates in the ManualSpecRunner.html file to:
<code>
  src="/../angular/angular.js"
</code>
Given the path starts with /, the location is incorrect.  Is there a way to reference/load sources in directories outside the project that is under test?

**Comment by kermit-the-frog** [comment]
The bug still seems to exist
`<source>${project.basedir}/../externalresources/src/main/resources/com/jquery/js/jquery-3.4.1.min.js</source>`
is converted to 
`<script type="application/javascript" src="/../externalresources/src/main/resources/com/jquery/js/jquery-3.4.1.min.js"></script>`

**Comment by kermit-the-frog** [comment]
I've found a solution:

```
<additionalContexts>
    <context>
        <contextRoot>externalresources</contextRoot>
        <directory>${project.basedir}/../externalresources/src/main/resources/</directory>
    </context>
</additionalContexts>
<preloadSources>
    <source>externalresources/com/jquery/js/jquery-3.4.1.min.js</source>
</preloadSources>
```
