### ISSUE TITLE
HTMLUnitDriver- Doesnt get the id attribute of div elements in the DOM

### ISSUE THREAD

**Issue by gowrav927** [searls/jasmine-maven-plugin#260]
we encountered a Scenario when using Jasmine:test during “mvn clean install”.
When we tried to compile a HTML Template in the Jasmine Specs and appended that to the HTML BODY tag, we noticed a condition where the “id” attribute for none of the html tags are compiled and placed in the generated html.

This happens only for the “id” attribute for DOM Elements, other attributes like “class” works fine.
But this scenario doesn’t happen when we run the same test file via the browser using jasmine:bdd

An example of the above scenario :

describe('Constructor ', function() { 
        beforeEach(function () { 
               inject(function($rootScope, $compile, $controller) {
                    $('body').append($compile('<div id="fixture"><div id="toolbar">cat</div></div>’)(scope)); 
                       scope.$digest(); 
                  });
               });
           it('sets a blank map if no map is passed in', function() {
             expect($(“#toolbar”).text().toBe(“cat”));   //Couldn’t get reference to the div tag “toolbar”
              });  
      });
The above code works during  Jasmine:bdd ,
But,
Fails during mvn clean install.
The reason we believe is the HTMLUnitDriver generating the HTML the id attributes for the div tag are not being added, so in a sense the page’s HTML ,loads up like this during jasmine:test
       <div id =” ”><div id=” ”>cat</div></div>
This is how the div tags are represented when we do a maven clean install and run the jsamine specs
But when we do the same run using jasmine:bdd (Browser way of runnin the test)
We get
                  <div id =”fixture ”><div id=” toolbar”>cat</div></div>
The div tags have the proper  values for the id attribute so everthing works fine.
We think bug is introduced when we load HTMLUnitDriver renders the web pages during testing.
So we overcame this scenario by using the PhantomJS.

**Comment by klieber** [comment]
Closing this since it worked with PhantomJS and that is now the default webdriver
