### ISSUE TITLE
jasmine:bdd is not running the same Specs/config as mvn test

### ISSUE THREAD

**Issue by ashleyfrieze** [searls/jasmine-maven-plugin#263]
I am trying to test the files from my main/webapp/js directory with some extra resources in test/js and my spec files in test/js. With the configuration (below) I find that maven is correctly executing my tests, but the web server behind mvn jasmine:bdd is still defaulting to the main/javascript and test/javascript source directories.

User error? or something else?

		    <plugin>
		      <groupId>com.github.klieber</groupId>  
		      <artifactId>phantomjs-maven-plugin</artifactId>
		      <version>0.4</version>
		      <executions>
		        <execution>
		          <goals>
		            <goal>install</goal>
		          </goals>
		        </execution>
		      </executions>
		      <configuration>
		        <version>1.9.7</version>
		      </configuration>
		    </plugin>
		    <plugin>
		      <groupId>com.github.searls</groupId>
		      <artifactId>jasmine-maven-plugin</artifactId>
		      <version>1.3.1.5</version>
		      <executions>
		        <execution>
		          <goals>
		            <goal>test</goal>
		          </goals>
		          <configuration>
					<jsSrcDir>${project.basedir}${file.separator}src${file.separator}main${file.separator}webapp${file.separator}js</jsSrcDir>
					<jsTestSrcDir>${project.basedir}${file.separator}src${file.separator}test${file.separator}js</jsTestSrcDir>
					<preloadSources>
					  <source>jquery.min.js</source>
					  <source>bootstrap.min.js</source>
					  <source>angular.min.js</source>
					  <source>angular-mocks.js</source>
					</preloadSources>
					<sourceIncludes>
					  <include>app.js</include>
					</sourceIncludes>
					<specIncludes>
						<include>*Test.js</include>
					</specIncludes>		  
				  
		            <webDriverClassName>org.openqa.selenium.phantomjs.PhantomJSDriver</webDriverClassName>
		            <webDriverCapabilities>
		              <capability>
		                <name>phantomjs.binary.path</name>
		                <value>${phantomjs.binary}</value>
		              </capability>
		            </webDriverCapabilities>
		          </configuration>
		        </execution>
		      </executions>
		    </plugin>

**Comment by klieber** [comment]
You need to move your configuration outside of the execution block.

**Comment by ashleyfrieze** [comment]
Thanks. That's the magic. Brilliant plug-in. Does exactly what it ought to!
