### ISSUE TITLE
Jasmine 2.0 release

### ISSUE THREAD

**Issue by markewallace** [searls/jasmine-maven-plugin#265]
Is there a planned date for the Jasmine 2.0 release?

**Comment by dsyer** [comment]
The alpha version is working for me (really nice to be able to load webjars), but it would be nice to get an update on this since the docs say it is subject to change.

**Comment by KramKroc** [comment]
Would love to see this too.

**Comment by mikehstrauss** [comment]
Me too...

**Comment by klieber** [comment]
Sorry this took so long.  Free time just isn't cheap these days: https://github.com/searls/jasmine-maven-plugin/releases/tag/jasmine-maven-plugin-2.0
