### ISSUE TITLE
Configuring HTMLUnit version?

### ISSUE THREAD

**Issue by tongc** [searls/jasmine-maven-plugin#272]
I have written some unit tests for our AngularJS application, the tests render the HTML template using Angular's $compile function. This works fine if I launch the tests using mvn jasmine:bdd but fails with mvn jasmine:test. 
I guess it is because of the version of HTMLUnit come with the plugin 1.3.1.5 or HTMLUnit just doesn't support Angular well. I can't upgrade to version 2.0 because its still in beta. 
I am going to give it a try by upgrading HTMLUnit version to latest 2.1.6 which seems to have fixed some Angular support issues. 
If this doesn't work I will try to use PhantomJS as headless browser.

**Comment by klieber** [comment]
You should be able to use the latest version of the plugin which is no longer in beta and includes built-in PhantomJS support. https://github.com/searls/jasmine-maven-plugin/releases/tag/jasmine-maven-plugin-2.1
