### ISSUE TITLE
outdated boot.js -> no beforeAll and afterAll in jasmineInterface

### ISSUE THREAD

**Issue by nahabi4** [searls/jasmine-maven-plugin#275]
Hi despite `jasmine-maven-plugin` uses  **jasmine 2.3.0**  used `boot.js` is outdated and not contain beforeAll and afterAll in jasmineInterface.

As result this functions give `ReferenceError: beforeAll is not defined` errors

**Comment by kermit-the-frog** [comment]
Any updates on this issue?

**Comment by jorahood** [comment]
Also wondering about this

**Comment by klieber** [comment]
Should be fixed in version `2.1`.
