### ISSUE TITLE
Unable to run jasmine-maven-plugin 2.0-beta-02 in Linux (Ubuntu)

### ISSUE THREAD

**Issue by harishkannarao** [searls/jasmine-maven-plugin#278]
Hi Team,
I started using jasmine-maven-plugin in my personal learning project for AngularJS.
The build works fine in Windows, however build fails in Ubuntu 14.04 (Linux).
I tried to get additional information through debug mode.
The error is 
Caused by: org.eclipse.aether.transfer.ArtifactNotFoundException: Failure to find com.github.klieber:phantomjs:tar.bz2:linux-x86_64:2.0.0 in https://repo.maven.apache.org/maven2

The plugin is trying to resolve an artifact not available in maven repository.
When I checked in maven central repository, I found that phantomjs binary version 2.0.0 is not available for linux operating system.
Link here http://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22com.github.klieber%22%20AND%20a%3A%22phantomjs%22

**Comment by mprins** [comment]
You´ll need to wait until after phantomjs releases a 2.0.0 for linux, or build it yourself. 
see: ariya/phantomjs#12948 and http://phantomjs.org/download.html

or you could just use phantomjs 1.9.8 using specifying that using [phantomjs](http://searls.github.io/jasmine-maven-plugin/test-mojo.html#phantomjs)

**Comment by harishkannarao** [comment]
Hi Team,
I have configured jasmine to use phantomjs 1.9.8 and it is running fine in Ubuntu.
Please close this issue.

A working example of this configuration is available in this githut pom.xml for reference.

https://github.com/harishkannarao/AngularJs/blob/master/dev-parent/angularjs-war/pom.xml
