### ISSUE TITLE
custom runner in combination with saga plugin?

### ISSUE THREAD

**Issue by ghost** [searls/jasmine-maven-plugin#279]
hi,

I'm trying to get jasmine-maven-plugin to run with the saga plugin to show test coverage.

The setup:
I am using a custom runner template to run the jasmine tests. In the custom runner, dependencies to necessary libraries are defined. The custom runner works successfully using the jasmine-maven-plugin.

The question:
The problem is when running the saga plugin using "http://localhost:${jasmine.serverPort}" as the basedir, it looks like the tests are not run using the custom runner.In this example(http://searls.github.io/jasmine-maven-plugin/code-coverage.html), a custom runner is not used. 
Does anyone have any experience using a custom runner to work  with jasmine-maven-plugin and saga plugin in combination?

Thank you.

**Comment by klieber** [comment]
A custom runner template should work with saga just fine so without an example project that is not working I can't really help.
