### ISSUE TITLE
Jasmine bdd very slow because it is searching too many files

### ISSUE THREAD

**Issue by brooklynphotos** [searls/jasmine-maven-plugin#282]
Loading the jetty server did not take more than a few seconds. Then pointing browser to a specific file, like /src/test/index.html took no time. But then if I wanted to try the root or /src, it took more than 6 MINUTES for the browser to get anything back. After a lot of testing, I realized that in the slow case, jasmine plugin is looking through all the directories in the directory where I am running mvn jasmine:bdd. That includes huge extjs directory, the build directory created by sencha cmd, which altogether contain tens of thousands of little text files. Is there a way to tell mvn jasmine:bdd to not look at everything? It seems the sourceIncludes or jsSrcDir merely tells the program to gather the names of source files in these directories; but it doesn't mean the program won't look at all the directories. Is that true? If so, is there a way for the program to look at specific places and not, say, the extjs library directory?

**Comment by mielw** [comment]
Did you manage to solve the problem? I got the same issue with my Ext Js test setup.

**Comment by blueberryfan** [comment]
I seem to have the same problem, but with the node_modules directory (where npm installs packages). If I delete the node_modules directory, my tests run in a couple of seconds, but with the directory there it takes more than a minute. Sometimes it times out. Seems like scanning the thousands of files in node_modules causes a problem.
How can I make the plugin completely ignore the npm node_modules directory?

I've tried to configure excludes like so, but none of them seem to make any difference. Am I missing something?

<configuration>
  ...
    <sourceExcludes>
                      <exclude>**/node_modules/**/*.*</exclude>

                      <exclude>myproj/subdirWithNodeStuff</exclude>
                      <sourceExclude>myproj/subdirWithNodeStuff</sourceExclude>

                      <exclude>myproj/subdirWithNodeStuff/**/*</exclude>
                      <sourceExclude>myproj/subdirWithNodeStuff/**/*</sourceExclude>

                      <exclude>myproj/subdirWithNodeStuff/node_modules</exclude>
                      <sourceExclude>myproj/subdirWithNodeStuff/node_modules</sourceExclude>
    </sourceExcludes>
</configuration>
