### ISSUE TITLE
Reliable reference to jasmine reporter

### ISSUE THREAD

**Issue by just-boris** [searls/jasmine-maven-plugin#285]
[Saga-maven-plugin](https://github.com/timurstrekalov/saga) is incompatible with 2.0 version of jasmine-maven-plugin. That happened because it detects end of jasmine tests via `window.reporter.finished` property. It was [here](https://github.com/searls/jasmine-maven-plugin/blob/jasmine-maven-plugin-1.3.1.6/src/main/resources/jasmine-templates/SpecRunner.htmltemplate#L32) in 1.3.x versions, but now it has gone and Saga can't detect the moment of finish tests.

Is there a new way to be sure that specs are finished? Found that [`SpecRunnerExecutor`](https://github.com/searls/jasmine-maven-plugin/blob/master/src%2Fmain%2Fjava%2Fcom%2Fgithub%2Fsearls%2Fjasmine%2Frunner%2FSpecRunnerExecutor.java#L115 ) now awaits of `window.jsApiReporter.finished`. Can I make that change in the Saga as well?

**Comment by klieber** [comment]
closing this since it was not an issue with the jasmine-maven-plugin.
