### ISSUE TITLE
Error message when compiling directive for maven:test

### ISSUE THREAD

**Issue by kbondsii** [searls/jasmine-maven-plugin#287]
Hi sorry if this issue has been resolved or is old.  I'm just having a difficult time finding anything on this.

I have a directive which I want to test.  It's a simple directive that takes in an attribute from scope and binds it for the template.  In my test spec, I use a simple test  (assume I inject dependencies)

it("tests for anything", function(){}
     scope.message = "Foobar";
     var compiledEl = compile(myDirective)(scope);    <--- this breaks it
     scope.$digest;
     var messageEl = compiledEl.find("span");
    //expectations follow
)

TypeError: Cannot find function trim in object message in http://localhost:53702/WebContent/lib/angular/angular.js(line 649)

It works great using jasmine:bdd but I have a build dependency on jasmine tests and it breaks every time.  

I do not use Karma due to some network prohibitions which keep me from using NPM altogether.  I use the jasmine-maven-plugin version 1.3.1.6 with jquery 1.10.2 and angular.js version 1.3.6.   All my other tests work except for those in directives so I'm assuming its a user error but not sure since I haven't found anything else.  FYI, I changed my entire directive to just an empty div and it still breaks after I remove everything from the compile, even the attributes.  I have also tried preloading the directive in the pom.  Not sure where to go from here.

**Comment by dharmapoudel** [comment]
Did you figure out the cause? I'm also having the exact same problem.

**Comment by kbondsii** [comment]
What I found was there is a bug in the plugin that misinterprets the
template param for directives.  It's a known and reported issue for this
version of the plugin.  There were some hacky ways to get around it, but I
just decided to skip directives in my testing efforts until I upgrade to a
later version of the plugin.  I haven't had a chance to upgrade yet
though.

**Comment by wimrutgeerts** [comment]
Hi,

Could you give us the hacky ways to get around it? It would help us a lot.

Kind regards
Freddy
