### ISSUE TITLE
Allow usage of a phantomjs binary globally available in the $PATH

### ISSUE THREAD

**Issue by lastnico** [searls/jasmine-maven-plugin#289]
With the new way of downloading automatically the PhantomJS binary, there is unfortunately a new drawback that popped out: it is know impossible to rely on a phantomjs binary that is simply available in the $PATH, without having to provide the absolute path to this binary. 

Indeed, in my enterprise environment where executables can be launched from specific folders only, the self-extracted phantomjs binary is per default at the wrong place. 

Using 

```xml
<webDriverClassName>org.openqa.selenium.phantomjs.PhantomJSDriver</webDriverClassName>
<webDriverCapabilities>
  <capability>
    <name>phantomjs.binary.path</name>
    <value>phantomjs</value>
  </capability>
</webDriverCapabilities>
```

does not help, as the "phantomjs" value will then be considered relative to current Maven project. 

Hence, this is to me a regression, as I don't see anyway from the jasmine-maven-plugin or from the phantomjs-maven-plugin Maven plugins to simply say: just use the first phantomjs binary found in the $PATH.

There _are_ workarounds, but none of them are satisfying me, compared to the basic need I have to just provide the phantomjs binary in the $PATH:
- Setting the outputDirectory of phantomjs-maven-plugin is a possibility, though, but it makes the pom.xml not being environment agnostic)
- Defining the binary path from the Maven command line
- Defining an environment variable

**Comment by klieber** [comment]
Please read the docs:
http://kylelieber.com/phantomjs-maven-plugin/install-mojo.html#enforceVersion

http://kylelieber.com/phantomjs-maven-plugin/install-mojo.html#checkSystemPath

**Comment by lastnico** [comment]
Hi,

Sorry, but the configuration below

```xml
<!-- Provide automatically PhantomJS binary to Jasmine Maven plugin -->
			<plugin>
				<groupId>com.github.klieber</groupId>
				<artifactId>phantomjs-maven-plugin</artifactId>
				<version>0.7</version>
				<executions>
					<execution>
						<goals>
							<goal>install</goal>
						</goals>
					</execution>
				</executions>
				<configuration>
					<checkSystemPath>true</checkSystemPath>
					<enforceVersion>2.3.0</enforceVersion>
					<version>2.0.0</version>
				</configuration>
			</plugin>

			<plugin>
				<groupId>com.github.searls</groupId>
				<artifactId>jasmine-maven-plugin</artifactId>
				<version>2.0</version>
				<executions>
					<execution>
						<goals>
							<goal>test</goal>
						</goals>
					</execution>
				</executions>
				
				<configuration>
					<webDriverClassName>org.openqa.selenium.phantomjs.PhantomJSDriver</webDriverClassName>
					<webDriverCapabilities>
						<capability>
							<name>phantomjs.binary.path</name>
							<value>${phantomjs.binary}</value>
						</capability>
					</webDriverCapabilities>

 					<sourceEncoding>utf-8</sourceEncoding>
 					
 					<goalPrefix>jasmine</goalPrefix>
				</configuration>
			</plugin>
```

... still make Maven using the phantomjs downloaded by the phantomjs-maven-plugin, not the one on the $PATH.

**Comment by klieber** [comment]
You have multiple issues with your config:

1. Starting with the 2.0 version of the jasmine-maven-plugin phantomjs is the default and you should not need to use the phantomjs-maven-plugin directly.

2. If you want to configure how phantomjs us resolved just use the phantomjs parameter: http://searls.github.io/jasmine-maven-plugin/test-mojo.html#phantomjs

3. If you have enforceVersion set to 2.0.0 then you must have that exact version installed on the path otherwise it will be downloaded.

Again, please read the documentation.

**Comment by lastnico** [comment]
Yes, I tried this alternative this morning:

PhantomJS is available on the path:
```
$workspace> phantomjs -v
2.0.0
```

```xml
<plugin>
				<groupId>com.github.searls</groupId>
				<artifactId>jasmine-maven-plugin</artifactId>
				<version>2.0</version>
				<executions>
					<execution>
						<goals>
							<goal>test</goal>
						</goals>
					</execution>
				</executions>
				
				<configuration>
...
				
					<phantomjs>
					  <version>2.0.0</version>
					  <checkSystemPath>true</checkSystemPath>
					  <enforceVersion>2.0.0</enforceVersion>
  					</phantomjs>

 					<sourceEncoding>utf-8</sourceEncoding>
 					
 					<goalPrefix>jasmine</goalPrefix>
				</configuration>
			</plugin>
```

But it ends up the same way, with the downloaded PhantomJS being used.

**Comment by lastnico** [comment]
Did you have a chance to test this particular case? 

Note I am on Windows (anyway PhantomJS 2.0.0 is not available on Linux, so it should be a clue, already ;)

**Comment by lastnico** [comment]
Any news on this bug?

**Comment by klieber** [comment]
I have not been able to reproduce it. I would suggest you create a sample
project that demonstrates your problem.

**Comment by lastnico** [comment]
You were right from the beginning, it's working as expected. It seems i was not able to cleanup my $PATH properly. Thanks!
