### ISSUE TITLE
Javascript Rest Parameters cause a build to error

### ISSUE THREAD

**Issue by moogleberry** [searls/jasmine-maven-plugin#291]
When building (maven clean install) a project using jasmine-maven-plugin, if the included Javascript files contain a function that uses a [Rest Parameter](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/rest_parameters), the build will yield a `JavaScript Console Error: Syntax Error: Parse Error` with no further explanation, and stop at `Failed to execute goal com.github.searls:jasmine-maven-plugin:2.0:test (default) ...`.  This error then causes a `java.lang.RuntimeException: There were javascript console errors.` that will cause the build to fail.  

I've traced the source to my use of a Rest Parameter in a function:
`var test = function(f, ...config) { ... };`
Removing the "..." in the parameter is sufficient to make the build finish successfully (but the functionality is then changed).  

Versions used: Maven 3.3.3, jasmine-maven-plugin 2.0, phantomjs 1.9.7, Java 1.8

I'm not sure if this is a jasmine-maven-plugin problem, or if I should be pushing this to apache-maven (or maybe it's just me?), since it references org.apache.maven.MavenCli.  Any suggestions?

**Comment by mprins** [comment]
you should probably take your report to the javascript engine issue tracker, phantomjs in this case; I'm guessing it does not support this ES 6 language feature atm.

**Comment by moogleberry** [comment]
Ok, thanks for the direction!

**Comment by klieber** [comment]
Closing this issue as it is not an issue with the plugin.  As soon as phantomjs supports these feature the plugin will but until then it is out of my control.
