### ISSUE TITLE
Jasmine-Maven Plugin Error with Maven Build

### ISSUE THREAD

**Issue by nareshreddy143** [searls/jasmine-maven-plugin#295]
I am using following plugin(jasmine-maven-plugin) with Maven version - 3.2.5. I am getting error of Failed to execute goal com.github.searls:Jasmine-maven-plugin:2.0:test.
Any Solution will be much appreciated Thanks in advance.

<plugin>

```
                          <groupId>com.github.klieber</groupId>
                          <artifactId>phantomjs-maven-plugin</artifactId>
                          <version>0.4</version>
                            <executions>
                                <execution>
                                    <goals>
                                        <goal>install</goal>
                                    </goals>
                                </execution>
                            </executions> 
                            <configuration>
                                <version>1.9.7</version>                  
                            </configuration>

      </plugin> 
        <plugin>
                           <groupId>com.github.searls</groupId>
                           <artifactId>jasmine-maven-plugin</artifactId>
                           <version>2.0</version>
                               <executions>
                                  <execution>
                                      <goals>
                                        <goal>test</goal>

                                      </goals>
                                      <configuration>
                                            <preloadSources>
                                                 <source>${project.basedir}/src/main/webapp/jasmine/*.js</source>
                                                 <source>${project.basedir}/src/main/webapp/ext/build/*.js</source>
                                            </preloadSources>
                                            <specIncludes>
                                                <include>${project.basedir}/src/main/webapp/spec/*.js</include>
                                            </specIncludes>
                                           <customRunnerTemplate>${project.basedir}/src/main/webapp/SpecRunner.html</customRunnerTemplate>
                                            <webDriverClassName>org.openqa.selenium.phantomjs.PhantomJSDriver</webDriverClassName>  
                                          <webDriverCapabilities>
                                            <capability>
                                              <name>phantomjs.binary.path</name>
                                             <value>${phantomjs.binary}</value> 
                                              <!-- <value>/apps/Senchabin/Sencha/Cmd/6.1.1.76/bin/windows/phantomjs/phantomjs.exe</value>  -->
                                            </capability>
                                          </webDriverCapabilities>
                                      </configuration>
                                  </execution>
                              </executions>

        </plugin>
```

I am using above plugin in my Maven build i am getting following Error
[DEBUG] STOPPED org.eclipse.jetty.server.Server@3fb0ea5a
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] ClientTrading Parent ............................... SUCCESS [  0.530 s]
[INFO] ClientTrading Config - DEV ......................... SUCCESS [  3.729 s]
[INFO] Prime MoneyMarket Web Config ....................... SUCCESS [  0.109 s]
[INFO] Prime MoneyMarket Web Java ......................... SUCCESS [  3.354 s]
[INFO] Prime MoneyMarket Web Application .................. FAILURE [06:51 min]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 07:00 min
[INFO] Finished at: 2016-05-03T15:00:20-04:00
[INFO] Final Memory: 21M/122M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.github.searls:jasmine-maven-plugin:2.0:test (default) on project clienttrading-web: The jasmine-maven-plugin encountered an exception:
[ERROR] java.lang.RuntimeException: org.openqa.selenium.TimeoutException: Timed out after 300 seconds waiting for com.github.searls.jasmine.runner.SpecRunnerExecutor$1@7b390e5e
[ERROR] Build info: version: '2.45.0', revision: '5017cb8e7ca8e37638dc3091b2440b90a1d8686f', time: '2015-02-27 09:10:26'
[ERROR] System info: host: 'v10033981', ip: '10.76.185.38', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.7.0_79'
[ERROR] Session ID: 943e43e0-1160-11e6-a6bc-ffb70dc1313a
[ERROR] Driver info: org.openqa.selenium.phantomjs.PhantomJSDriver
[ERROR] Capabilities [{platform=XP, acceptSslCerts=false, javascriptEnabled=true, browserName=phantomjs, rotatable=false, driverVersion=1.1.0, locationContextEnabled=false, version=1.9.7, cssSelectors
Enabled=true, databaseEnabled=false, handlesAlerts=false, browserConnectionEnabled=false, proxy={proxyType=direct}, nativeEvents=true, webStorageEnabled=false, driverName=ghostdriver, applicationCache
Enabled=false, takesScreenshot=true}]
[ERROR] at com.github.searls.jasmine.runner.SpecRunnerExecutor.execute(SpecRunnerExecutor.java:53)
[ERROR] at com.github.searls.jasmine.mojo.TestMojo.executeSpecs(TestMojo.java:236)
[ERROR] at com.github.searls.jasmine.mojo.TestMojo.run(TestMojo.java:204)
[ERROR] at com.github.searls.jasmine.mojo.AbstractJasmineMojo.execute(AbstractJasmineMojo.java:385)
[ERROR] at com.github.searls.jasmine.mojo.TestMojo.execute(TestMojo.java:191)
[ERROR] at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:132)
[ERROR] at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
[ERROR] at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
[ERROR] at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
[ERROR] at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
[ERROR] at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
[ERROR] at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
[ERROR] at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:120)
[ERROR] at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:355)
[ERROR] at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:155)
[ERROR] at org.apache.maven.cli.MavenCli.execute(MavenCli.java:584)
[ERROR] at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:216)
[ERROR] at org.apache.maven.cli.MavenCli.main(MavenCli.java:160)
[ERROR] at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR] at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
[ERROR] at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR] at java.lang.reflect.Method.invoke(Method.java:606)
[ERROR] at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
[ERROR] at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
[ERROR] at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
[ERROR] at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
[ERROR] Caused by: org.openqa.selenium.TimeoutException: Timed out after 300 seconds waiting for com.github.searls.jasmine.runner.SpecRunnerExecutor$1@7b390e5e
[ERROR] Build info: version: '2.45.0', revision: '5017cb8e7ca8e37638dc3091b2440b90a1d8686f', time: '2015-02-27 09:10:26'
[ERROR] System info: host: 'v10033981', ip: '10.76.185.38', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.7.0_79'

**Comment by klieber** [comment]
This is likely an issue with one of your tests or the custom spec runner you are using and not the plugin. Without an example project replicating an issue I can't say that for sure.  Also, starting with version `2.0` you don't need to use the `phantomjs-maven-plugin` because it's built-in to the `jasmine-maven-plugin` and [PhantomJS is the default now](http://searls.github.io/jasmine-maven-plugin/phantomjs.html).  You can configure it using the [phantomjs configuration parameter](http://searls.github.io/jasmine-maven-plugin/test-mojo.html#phantomjs)).  So, you can simplify your configuration:

```xml
<plugin>
  <groupId>com.github.searls</groupId>
  <artifactId>jasmine-maven-plugin</artifactId>
  <version>2.1</version>
  <executions>
    <execution>
      <goals>
        <goal>test</goal>
      </goals>
      <configuration>
        <phantomjs>
          <version>2.1.1</version>
        </phantomjs>
        <preloadSources>
          <source>src/main/webapp/jasmine/*.js</source>
          <source>src/main/webapp/ext/build/*.js</source>
        </preloadSources>
        <specIncludes>
          <include>src/main/webapp/spec/*.js</include>
        </specIncludes>
        <customRunnerTemplate>src/main/webapp/SpecRunner.html</customRunnerTemplate>
        <haltOnFailure>true</haltOnFailure>
      </configuration>
    </execution>
  </executions>
</plugin>
```

For any further help I would need a sample project replicating the issue with version `2.1` of the plugin using a configuration similar to above.

**Comment by Schwasrz94** [comment]
I am getting the same error on travis ci:
https://travis-ci.org/openmrs/openmrs-module-radiology/jobs/151195323
I am not using a custom spec runner and on local build everything works fine.
The curious thing is that until yesterday the error had not occurred.
Thanks for your help!

`			<plugin>
				<groupId>com.github.searls</groupId>
				<artifactId>jasmine-maven-plugin</artifactId>
				<version>2.1</version>
				<configuration>
					<phantomjs>
						<version>2.1.1</version>
						<checkSystemPath>true</checkSystemPath>
						<enforceVersion>true</enforceVersion>
						<source>REPOSITORY</source>
						<baseUrl />
						<outputDirectory>target/phantomjs</outputDirectory>
					</phantomjs>
					<jsSrcDir>${project.basedir}/src/main/webapp/resources/scripts</jsSrcDir>
					<preloadSources>
						<source>helpers/jquery-1.8.1.js</source>
						<source>helpers/jasmine-jquery.js</source>
						<source>helpers/definitions.js</source>
					</preloadSources>
					<sourceIncludes>
						<include>radiology.js</include>
					</sourceIncludes>
					<sourceExcludes>
						<exclude>**/jquery/*.*</exclude>
						<exclude>**/tinymce/*.*</exclude>
						<exclude>**/moment/*.*</exclude>
					</sourceExcludes>
					<jsTestSrcDir>${project.basedir}/src/test/javascript</jsTestSrcDir>
					<specIncludes>
						<include>**/*Spec.js</include>
					</specIncludes>
				</configuration>
				<executions>
					<execution>
						<goals>
							<goal>test</goal>
						</goals>
					</execution>
				</executions>
			</plugin>`

**Comment by ramesht05** [comment]
Hi, 
This configuration works just fine in Unix & OS X environments
<plugin>
                <groupId>com.github.searls</groupId>
                <artifactId>jasmine-maven-plugin</artifactId>
                <version>2.0</version>
                <executions>
                    <execution>
                        <id>jasmine-tests</id>
                        <phase>test</phase>
                        <goals>
                            <goal>test</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <additionalContexts>
                        <context>
                            <contextRoot>templates</contextRoot>
                            <directory>${project.basedir}/src/main/resources/static/templates</directory>
                        </context>
                    </additionalContexts>
                    <jsSrcDir>${project.basedir}/src/main/resources/static/javascript</jsSrcDir>
                    <jsTestSrcDir>${project.basedir}/src/test/resources/static/javascript</jsTestSrcDir>
                       <webDriverClassName>org.openqa.selenium.phantomjs.PhantomJSDriver</webDriverClassName>
                    <webDriverCapabilities>
                        <capability>
                            <name>phantomjs.binary.path</name>
                            <value>${project.basedir}/node_modules/phantomjs-prebuilt/lib/phantom/bin/phantomjs</value>
                        </capability>
                    </webDriverCapabilities>
                </configuration>
            </plugin>
but, when I try to run this maven build on Windows platform it throws an error saying
"java.lang.IllegalStateException: The driver executable does not exist:"

I could make it build by changing the below line 
<value>${project.basedir}/node_modules/phantomjs-prebuilt/lib/phantom/bin/phantomjs.exe</value>

My question is, how to make this configuration platform independent? How can I make this more generic so that I don't have to keep changing the pom for every platform.

**Comment by aquator** [comment]
We have similar issues when working with --threads, but it is inconsistent.
