### ISSUE TITLE
ECMAScript 6 Arrow Functions - Unexpected Token '>'

### ISSUE THREAD

**Issue by RicoSchueppel** [searls/jasmine-maven-plugin#304]
We currently develop an Java Spring Boot app using an AngularJs FrontEnd (as static resources). 
For unit testing of AngularJs controllers , we use Maven integrated Jasmine (com.github.searls / jasmine-maven-plugin / version 2.1) and that uses PhantomJs V2.1.1.

When I start the app via console `mvn clean install spring-boot:run` or just `mvn jasmine:test`, the maven test goal fails and I get the following error:

> [WARNING] JavaScript Console Errors:
> 
>   * SyntaxError: Unexpected token '>'
>   * SyntaxError: Unexpected token '>'

When I start test server using `mvn jasmine:bdd` or directly from IDE (Eclipse) with a jasmine test app, the jasmine test server and all tests work very well (without any error, all tests ok). Chrome does also not show any errors on console. 

I googled some hours to find any reason for that. In other blogs, I found some hints that PhantomJs v2 possibly does not support some parts of ECMAScript 6 (lambdas / arrow functions, like (x) => {do something with x here}).

I kicked those lambdas out and replaced it by plain old function calls. **Now `mvn jasmine:test` works fine**. By the way, the lambdas were used in a file that was not required for testing, thus not necessarily executed. It was just included by plugin configuration via `jsSrcDir`.

Is there any other solution than kicking out lambdas? Can I somehow use jasmine-maven-plugin / phantomjs with js files that have lambdas / arrow functions in it?

**Comment by klieber** [comment]
If phantomjs doesn't support it then it's out of the plugins control. I suggest opening an issue with the phantomjs project. A workaround might be configuring the plugin to use chrome instead of phantomjs.
