### ISSUE TITLE
classname cannot be modified

### ISSUE THREAD

**Issue by gyuhan87** [searls/jasmine-maven-plugin#308]
https://github.com/searls/jasmine-maven-plugin/blob/88e4387b52361442b7a70c84cd2e3625258d4ae2/src/main/resources/lib/createJunitXml.js

From this file, 'classname' is hardcoded to 'jasmine'.
Is there any way to change the classname when the test rusult is composed?

**Comment by klieber** [comment]
Currently there is no way to change it.  Pull requests will be considered if you would like to enhance the JUnit report.
