### ISSUE TITLE
no way to disable/enable warnings coming from HtmlUnit

### ISSUE THREAD

**Issue by xsocher** [searls/jasmine-maven-plugin#31]
any possibilities to turn off/on the chatty htmlUnit error messages in this plugin?

16.09.2011 11:49:31 com.gargoylesoftware.htmlunit.DefaultCssErrorHandler error
WARNUNG: CSS error: null [8:438] Fehler in Ausdruck. Ungültiger Token "=". Erwartet wurde einer von: <S>, <COMMA>, "/", <PLUS>, "-", <HASH>, <
STRING>, ")", <URI>, "inherit", <EMS>, <EXS>, <LENGTH_PX>, <LENGTH_CM>, <LENGTH_MM>, <LENGTH_IN>, <LENGTH_PT>, <LENGTH_PC>, <ANGLE_DEG>, <ANGL
E_RAD>, <ANGLE_GRAD>, <TIME_MS>, <TIME_S>, <FREQ_HZ>, <FREQ_KHZ>, <DIMENSION>, <PERCENTAGE>, <NUMBER>, <FUNCTION>, <IDENT>.
16.09.2011 11:49:31 com.gargoylesoftware.htmlunit.DefaultCssErrorHandler error
WARNUNG: CSS error: null [8:443] Fehler in Style-Regel. Ungültiger Token "opacity". Erwartet wurde einer von: "}", ";".
http://htmlunit.sourceforge.net/faq.html#AJAXDoesNotWork

reference:http://htmlunit.sourceforge.net/faq.html#AJAXDoesNotWork

**Comment by klieber** [comment]
Closing this issue because it hasn't been active in over 3 years.  If this is still an issue with the current version of the plugin please add a comment with the latest information on the issue and I will reopen it.
