### ISSUE TITLE
Autowatch / Autoreload mode?

### ISSUE THREAD

**Issue by LeeU1911** [searls/jasmine-maven-plugin#311]
Hi all,

Thank you for this amazing plugin!

I'm wondering if there's an autowatch mode so that it watches for changes in my source/test code and  reload my browser automatically?

Thanks again,
Vu

**Comment by klieber** [comment]
Try the `autoRefreshInterval` parameter: https://searls.github.io/jasmine-maven-plugin/bdd-mojo.html#autoRefreshInterval

**Comment by LeeU1911** [comment]
Thank you Kyle. I tried this and it works as its name implies. But I would really love to have something that watches my stuffs for changes and I can then debug/refresh as I need, instead of auto refresh every 5 or 10 seconds. 

Do you think it's feasible? I can take a look into the source and try to come up with something if you see it's doable.

Best,
Vu
