### ISSUE TITLE
Jasmine-Maven plugin error in Windows platform

### ISSUE THREAD

**Issue by ramesht05** [searls/jasmine-maven-plugin#313]
Hi,
I'm getting an error in the maven build on my Windows environment. 

The below configuration works just fine in Unix & OS X environments

```
<plugin>
    <groupId>com.github.searls</groupId>
    <artifactId>jasmine-maven-plugin</artifactId>
    <version>2.0</version>
    <executions>
        <execution>
            <id>jasmine-tests</id>
            <phase>test</phase>
            <goals>
                <goal>test</goal>
            </goals>
        </execution>
    </executions>
    <configuration>
        <additionalContexts>
            <context>
                <contextRoot>templates</contextRoot>
                <directory>${project.basedir}/src/main/resources/static/templates</directory>
            </context>
        </additionalContexts>
        <jsSrcDir>${project.basedir}/src/main/resources/static/javascript</jsSrcDir>
        <jsTestSrcDir>${project.basedir}/src/test/resources/static/javascript</jsTestSrcDir>
           <webDriverClassName>org.openqa.selenium.phantomjs.PhantomJSDriver</webDriverClassName>
        <webDriverCapabilities>
            <capability>
                <name>phantomjs.binary.path</name>
                <value>${project.basedir}/node_modules/phantomjs-prebuilt/lib/phantom/bin/phantomjs</value>
            </capability>
        </webDriverCapabilities>
    </configuration>
</plugin>
```

but, when I try to run this maven build on Windows platform it throws an error saying
"java.lang.IllegalStateException: The driver executable does not exist:"

I could make it build successfully by changing the below line
${project.basedir}/node_modules/phantomjs-prebuilt/lib/phantom/bin/phantomjs.exe

My question is, how to make this configuration platform independent? How can I make this more generic so that I don't have to keep changing the pom for every platform.

**Comment by klieber** [comment]
Starting with version `2.0` of the plugin PhantomJS is the default and it is installed for you automatically if needed.  So, I would suggest just letting the plugin take care of it by getting rid of the `webDriverClassName` and `webDriverCapabilities` parameters.  If for some reason you need to use the version from NodeJS well then you are welcome to try but that is not supported so you'll have to figure that one at yourself.

I would also suggest upgrading to the latest version of the plugin which is `2.2`.
