### ISSUE TITLE
How to use phantomjs 2.1.1

### ISSUE THREAD

**Issue by kermit-the-frog** [searls/jasmine-maven-plugin#319]
Hi,

how can I tell jasmine-maven-plugin to use phantomjs 2.1.1?

Kind regards,
kermit-the-frog

**Comment by klieber** [comment]
Please read the docs: http://searls.github.io/jasmine-maven-plugin/test-mojo.html#phantomjs

Also, please use StackOverflow for questions like this in the future. Just tag the question with jasmine-maven-plugin.
