### ISSUE TITLE
timeout error after waiting for 300 sec with version 3.0-beta-01

### ISSUE THREAD

**Issue by borncodeguru** [searls/jasmine-maven-plugin#368]
I am trying to write unit test for java script code. This is using JQuery as also. I am using jasmine-maven-plugin version 3.0-beta-01. When I run command "mvn clean test", it print below.

**_[INFO] Executing Jasmine Specs ChromeDriver was started successfully. Sep 22, 2020 11:16:21 PM org.openqa.selenium.remote.ProtocolHandshake createSession INFO: Detected dialect: W3C [WARNING] Attempted to wait for your specs to finish processing over the course of 300 seconds, but it still appears to be running. [INFO] ------------------------------------------------------------------------ [INFO] BUILD FAILURE_**

Why it keeps waiting? should it not run spec and exit? Just to ensure that there is no problem with spec I kept spec very simple and added only test as below

_**describe("User", function() {
    describe("UserBadges", function() {
      
        it("test to get badges table columns", function() {
            expect(2).toBe(2);
        });
    });
});**_

Can someone please help on this? Am I missing any configuration?

**Comment by klieber** [comment]
Can you please provide a full example in a git repo demonstrating the problem?  Hard for me to say what the problem is without it.

**Comment by borncodeguru** [comment]
I realized that a similar issue already exists https://github.com/searls/jasmine-maven-plugin/issues/348. so closing this thread.
