### ISSUE TITLE
jasmine:bdd (version 3.0-beta-01) opens browser but jetty gives 403

### ISSUE THREAD

**Issue by ggruber4711** [searls/jasmine-maven-plugin#379]
I have just tried to migrate my maven project jasmine setup from using 2.2 to 3.0-beta-01 in order to use the newer version which uses the headless chrome browser.

The cli run using `mvn jasmine:test` works fine, however the bdd version via `mvn jasmine:bdd` results in permission problem of jetty returning a 403.

![image](https://user-images.githubusercontent.com/3330414/97308389-1baaba00-1861-11eb-86f0-85324905cdf3.png)

**Comment by klieber** [comment]
@ggruber4711 can you provide a sample project that recreates the problem?  I'm not seeing that issue so likely it's specific to your project or environment.
