### ISSUE TITLE
haltOnFailure isn't strong enough

### ISSUE THREAD

**Issue by bimargulies** [searls/jasmine-maven-plugin#43]
Nov 2, 2011 10:28:47 AM com.gargoylesoftware.htmlunit.javascript.StrictErrorReporter error
SEVERE: error: message=[missing } after property list] sourceName=[file:/Users/benson/x/oap/it/jdd-rest/target/jasmine/spec/restTests.js] line=[21] lineSource=[        url: "http://localhost:" + jddServicePort + "/query/tasks";] lineOffset=[67]

leads to a failure.  This is a problem when trying to use this in an integration-test and you want to also run post-integration-test;

**Comment by klieber** [comment]
Closing this issue because it is over 4 years old and hasn't had any comments since it was first opened.  If this is still an issue with the current version of the plugin please add a comment with the latest information on the issue and I will reopen it.
